### ISSUE TITLE
importing from cmsgpack is not accepted by mypy even with msgpack-types installed

### ISSUE THREAD

**Issue by radkujawa** [sbdchd/msgpack-types#3]
My project strongly relies on fast msgpack C extension
we check if it is available by importing from `msgpack._cmsgpack` (the same method is used inside msgpack to decide if use the fallback mode)
it would be nice if mypy was recognizing types from inside the _cmsgpack submodule when msgpack-types installed.

**Comment by trim21** [comment]
according to source, `_cmsgpack` contains only `Packer, Unpacker, unpackb`, so this should fix this issue

https://github.com/sbdchd/msgpack-types/pull/6/files#diff-f6569ea2df970083d4c2dd0b97d71810a5c40ae361f8c55684d8cf5002b89d12
